/*
 * ServicioConsumible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.ProblemDetails;
import org.openapitools.client.model.ResultsResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for ResultadosApi
 */
@Disabled
public class ResultadosApiTest {

    private final ResultadosApi api = new ResultadosApi();

    
    /**
     * 
     *
     * 
     */
    @Test
    public void resultadosPostTest()  {
        String nombreUsuario = null;
        Integer tok = null;
        ResultsResponse response = api.resultadosPost(nombreUsuario, tok);

        // TODO: test validations
    }
    
}